/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ChildComponent {}
  interface ParentComponent {
    'event': boolean;
  }
}

declare global {


  interface HTMLChildComponentElement extends Components.ChildComponent, HTMLStencilElement {}
  var HTMLChildComponentElement: {
    prototype: HTMLChildComponentElement;
    new (): HTMLChildComponentElement;
  };

  interface HTMLParentComponentElement extends Components.ParentComponent, HTMLStencilElement {}
  var HTMLParentComponentElement: {
    prototype: HTMLParentComponentElement;
    new (): HTMLParentComponentElement;
  };
  interface HTMLElementTagNameMap {
    'child-component': HTMLChildComponentElement;
    'parent-component': HTMLParentComponentElement;
  }
}

declare namespace LocalJSX {
  interface ChildComponent {}
  interface ParentComponent {
    'event'?: boolean;
  }

  interface IntrinsicElements {
    'child-component': ChildComponent;
    'parent-component': ParentComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'child-component': LocalJSX.ChildComponent & JSXBase.HTMLAttributes<HTMLChildComponentElement>;
      'parent-component': LocalJSX.ParentComponent & JSXBase.HTMLAttributes<HTMLParentComponentElement>;
    }
  }
}


